---
name: EnvironmentCoordinates
description: |
  Coordinates origin (or zero), for gaze-on-screen coordinates,
  this can be for example: `"top-left"` or `"center"`.
  For virtual reality this could be, amongst others, spherical coordinates.
type: string
